CTSRD-CHERI/QuickCheckVEngine

src/QuickCheckVEngine/MainHelpers.hs

My regressiontest.py script depends on these warnings to distinguish
skipped tests from successful ones.
Not printing success would be even better, but I can't read/write Haskell.

Also print not running warning in non-verbose mode

---

src/QuickCheckVEngine/Main.hs
src/QuickCheckVEngine/MainHelpers.hs
src/QuickCheckVEngine/RVFI_DII/RVFI.hs
src/QuickCheckVEngine/Template.hs

This needs some tidying up + documenting, but seems to hold up to some makeshift testing.
In templates, there's now the Assert constructor, taking:
- A template to make assertions about
- A function from [RVFI_Report] to Bool that is expected to be true
- A string to print should the assert fail
It is expected the most common use will be around Single instructions, e.g.
`Assert (Single $ encode addi 13 0 5, \[x] -> rvfi_rd_wdata x == 13, "13 must be written back")`
A few deficiencies:
- No indication which instruction caused the assert fail - is it reasonable to expect the string is sufficient? In general, assertions need not cover a single instruction so it might not be clear which to refer to (the last one covered by the assert?)
- Not clear what behaviour to use when truncating the …

Support asserts in templates and saved traces

---

.gitignore
QCVEngine.cabal
src/QuickCheckVEngine/Main.hs
src/QuickCheckVEngine/MainHelpers.hs
src/QuickCheckVEngine/RVFI_DII.hs
src/QuickCheckVEngine/RVFI_DII/DII.hs
src/QuickCheckVEngine/RVFI_DII/RVFI.hs
src/QuickCheckVEngine/Template.hs
src/RISCV.hs
src/RISCV/Helpers.hs
src/RISCV/RV_CSRs.hs

This is backwards compatible, old implementations can still report
version1  traces and we won't compare fields that aren't present yet (e.g. privilege level).

V2 trace wire format

---

src/QuickCheckVEngine/Main.hs
src/RISCV/ArchDesc.hs

Otherwise we get lots of errors due to trapping on accesses to
mcountinhibit, etc.

Only run HPM tests when Zihpm is supported

---

stack.yaml
stack.yaml.lock

Now that we no longer need QuickCheck 2.12, but can use newer versions,
there is no need to use the 13.30 LTS resolver.
This allows me to get better code completion in IntelliJ.

Stack: Use a newer LTS resolver

---

QCVEngine.cabal

On my system (Debian 12) `ghc --version` reports 9.0.2, so I don't have 4.16 yet. It seems to build just fine against 4.15, so downgrade the requirement to 4.15.
This was changed in 7aad5ed0c0dfc724226425e474e74b139f35a581

Downgrade base requirement to 4.15

---

src/QuickCheckVEngine/RVFI_DII/RVFI.hs

I noticed that we weren't comparing all RVFI fields, this should fix it.
Needs https://github.com/riscv/sail-riscv/pull/208 to compare QEMU vs sail.

Compare full trace

---

src/QuickCheckVEngine/Templates/GenCHERI.hs
src/QuickCheckVEngine/Templates/GenTransExec.hs
src/QuickCheckVEngine/Templates/Utils/CHERI.hs
src/RISCV/RV32_Xcheri.hs

This was helpful finding divergences for the removal of PCC relocation.
Without this change I was able to run thousands of caprandom rounds without
finding a divergence.

Add a bounded PCC template

---

.github/workflows/haskell.yml
src/InstrCodec.hs
stack.yaml
stack.yaml.lock
weeder.dhall

Using https://github.com/freckle/stack-action

Add a basic GitHub Actions CI script

---

src/QuickCheckVEngine/Templates/Utils/Compressed.hs

Some compressed instructions use immediate bits above the range previously being generated.
Some instructions were using more bits than were being generated. Others were skipping LSBs to select higher bits only.
Instructions that set the upper limit on immediate bits required:
`C.J` / `C.JAL` (imm[11:...]),
`C.LQSP` / `C.SQSP` (uimm[9:...]),
`C.LUI` (nzimm[17:..]) (no increase required), and
`C.ADDI4SPN` (nzuimm[9:...])

Increase bits generated for RVC immediates

---

src/QuickCheckVEngine/Main.hs
src/QuickCheckVEngine/MainHelpers.hs
src/QuickCheckVEngine/RVFI_DII/RVFI.hs

Changed the `pedantic` option to be named `strict`. This also changes the default behaviour to relaxed comparisons.

Changed pedantic to strict and changed default behaviour

---

src/InstrCodec.hs

Modify `unscatter` so it works for instructions that do not encode the lowest bits of the immediate value provided to them. This issue has been hidden because many instructions have been encoded using the lower immediate bits rather than upper immediate bits (e.g. `imm[19:0]` rather than `imm[31:12]` for `lui`), and others (which do omit lower immediate bits) are not included in disassembly output (e.g. `c_lui` with empty `rv_c_disass`).
See also:
https://github.com/CTSRD-CHERI/QuickCheckVEngine/issues/41

Fix verbose print of instrs that omit low imm bits

---

src/RISCV/ArchDesc.hs

Since the value had come out of split, and the inputs are sanitised by argparse, this wasn't an actual issue, but it was generating some CI warnings.

Avoid type-unsafe use of 'head'

---

src/RISCV/RV32_Xcheri.hs

Before this change the existing CHERI templates did not generate the CMOVE instruction at all.

Generate cmove in miscellaneous instructions

---

src/QuickCheckVEngine/Main.hs
src/QuickCheckVEngine/MainHelpers.hs

This adds an option to QCVEngine to save all traces instead of just failures. I'm happy to implement any suggestions on how to do this in a cleaner way!

Add option to save all traces

---

src/RISCV/Helpers.hs
src/RISCV/InstInspect.hs
src/RISCV/RV_C.hs

Implement basic disassembly for RV_C (compressed instructions). Only the compressed instruction and given operands are shown in the printed output. No expansion to non-compressed instructions or insertion of implicit operands is performed.
Simplicity was the aim, given the high number array of special cases.

Add RV_C disassembly

---

src/RISCV/RV_C.hs

These `c_flq` & `c_fsq` instructions do not seem to exist in the ratified spec for the "C" extension.
Rename them to the `c_lq` & `c_sq` instructions that do appear in the spec and use the same encoding.
See Issue #53

Rename `c_flq` & `c_fsq` to `c_lq` & `c_sq`

---

src/QuickCheckVEngine/RVFI_DII/RVFI.hs

The data is presented in the written register in any case, so all this was testing is how the data is aligned in the report.

Relax comparing memory read data

---

src/QuickCheckVEngine/RVFI_DII/RVFI.hs
src/RISCV/Helpers.hs
src/RISCV/InstInspect.hs
src/RISCV/RV_C.hs

Add explicit HINT, Reserved, and NSE compressed instruction encodings from the spec.
This allows Templates to more easily specify these special encodings and enables more accurate disassembly.
Note that some encodings overlap.
Add new instruction disassembly pretty printer functions for special cases where the operands are uninteresting or ambiguous.
Rework the disassembly to account for overlapping encodings. Use XLEN, when available, and carful ordering to distinguish overlapping encodings from each other.
Present both encodings when encodings overlap and XLEN is not available.
Integrate new disassembly so that XLEN will be passed through when known (currently only for RVFI V2 packets).
Minor errors may remain.
Caution only goes so far when there are so many fiddly changes required.

Add RVC HINT/RES/NSE encs & rework disassembly

---

QCVEngine.cabal
src/QuickCheckVEngine/Main.hs
src/QuickCheckVEngine/Templates/GenUnstructured.hs

This is intended to be used in single-implementation mode to check that unknown bit patterns at least do not wedge the processor.
Goes some way towards addressing https://github.com/CTSRD-CHERI/QuickCheckVEngine/issues/60

Add 'unstructured' template that tests random instruction bit patterns

---

src/QuickCheckVEngine/Main.hs

This is useful for 'rigcover': coverage isn't accurate if sail is able to compare on v2 traces but the implementations only compare on v1.

Add option to force RVFIv1

---

QCVEngine.cabal
src/QuickCheckVEngine/Main.hs
src/QuickCheckVEngine/MainHelpers.hs
src/QuickCheckVEngine/RVFI_DII/DII.hs
src/QuickCheckVEngine/RVFI_DII/RVFI.hs
src/QuickCheckVEngine/TestTypes.hs
src/RISCV/Helpers.hs

As well as preventing frustrating bugs, this will allow us to be a lot less conservative with our shrinking rules!

Prevent shrink loops by keeping history when shrinking
